# Test your FastAPI endpoints

GET http://127.0.0.1:8000/api/v1/org/t2v/identity/u/spam@ore.ink/inventory/avatar
Accept: application/json

###

GET http://127.0.0.1:8000/api/v1/status/check?__token__=dev
Accept: application/json

###
